services:
  - type: web
    name: omnostock-waitlist
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: omnostock-db
          property: connectionString
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: MAILCHIMP_API_KEY
        sync: false

databases:
  - name: omnostock-db
    plan: free
    databaseName: omnostock
    user: omnostock