services:
  - type: web
    name: waitlist-app
    env: node
    plan: free
    buildCommand: rm -f package.json && cp package-new.json package.json
    startCommand: node standalone-server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        value: https://pnuolzmfajxwpofbbxbo.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBudW9sem1mYWp4d3BvZmJieGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDM1ODUsImV4cCI6MjA2NDYxOTU4NX0.qa-noNI-MGjYdHNYD04orbUZygvpERaOsihp0P4D5ag